import mongoose from "mongoose";

const RequestSchema = new mongoose.Schema({
  studentId: { type: mongoose.Schema.Types.ObjectId, ref: "Student" },
  subjectId: { type: mongoose.Schema.Types.ObjectId, ref: "Subject" },
  studentEmail: String,
  requestType: String,
  reason: String,
  currentMarks: Number,
  updatedMarks: Number,
  adminRemarks: String,
  responseSheet: String,
  amountPaid: Number,
  paymentMethod: { type: String, default: "Google Pay" },
  paymentStatus: {
    type: String,
    enum: ["pending", "success", "failed"],
    default: "pending"
  },
  transactionId: String, // String ID as generated by mock or could be ObjectId ref
  status: {
    type: String,
    enum: ["pending", "in_review", "approved", "rejected"],
    default: "pending"
  },
  createdAt: { type: Date, default: Date.now },
  updatedAt: Date,
});

export default mongoose.model("Request", RequestSchema);
